name: Actualizar Pronósticos
on:
  schedule:
    - cron: '0 23 * * *' # Se ejecuta todos los días a las 23:00
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Ejecutar motor predictivo
        env:
          API_KEY_FOOTBALL: ${{ secrets.API_KEY_FOOTBALL }}
        run: python generar_pronosticos.py

      - name: Guardar cambios
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add pronosticos.json
          git commit -m "Actualización automática de pronósticos" || echo "Sin cambios"
          git push
