name: Actualizar Pronosticos
on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Instalar librerias
        run: pip install pandas lxml html5lib

      - name: Ejecutar motor de extraccion
        run: python generar_pronosticos.py

      - name: Guardar cambios
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add pronosticos.json
          git commit -m "Actualizacion automatica diaria" || echo "Sin cambios"
          git push
